<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Oliver  Liam  Chris  Eve</name>
   <tag></tag>
   <elementGuidId>7588a48a-74b4-4358-b702-2075181a8dd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='agents']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#agents</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f0b6fae-5a08-4581-82e1-757c9f15ab5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agens</value>
      <webElementGuid>5da2bf32-1abf-4757-bae0-72c318e7bfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agents</value>
      <webElementGuid>c88c4ae8-967a-48e6-8e12-79d5cb5f827d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Oliver
  Liam
  Chris
  Eve
</value>
      <webElementGuid>b2f3a9e8-ca90-4f09-bc6f-e8c68401f835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agents&quot;)</value>
      <webElementGuid>bb0c59b8-ed6f-4065-875c-753be6a07ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='agents']</value>
      <webElementGuid>9fd62a9a-587f-4096-8d9d-06852de3a846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose an agent:'])[1]/following::select[1]</value>
      <webElementGuid>5cbaca43-c61b-490f-8e7d-8b42ee560787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'agents', '&quot;', ')/option[1]')])[1]/preceding::select[1]</value>
      <webElementGuid>31b6e83b-60b8-46a4-9a12-b3ff6eb74dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6a2d4681-ce9a-49b0-8138-6c0282b6d497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'agens' and @id = 'agents' and (text() = '
  Oliver
  Liam
  Chris
  Eve
' or . = '
  Oliver
  Liam
  Chris
  Eve
')]</value>
      <webElementGuid>e3131e30-f5cf-4cd9-8416-e2dc528d4683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
