<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Next_myFile</name>
   <tag></tag>
   <elementGuidId>aa89a510-0f57-4753-aa8b-95e10e308b8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myFile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='myFile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcf1b321-ebd5-4356-a5fc-3e022c71ff67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>08ed9423-b901-4edc-9aef-bb525820076a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myFile</value>
      <webElementGuid>b5526f78-98d4-4990-846c-046a64bfe3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myFile&quot;)</value>
      <webElementGuid>aa26c002-6567-4617-83ff-545d2ba17dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='myFile']</value>
      <webElementGuid>83bd15b4-324e-4c16-94cc-3b0cbb3d652a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/input</value>
      <webElementGuid>06df6d48-9444-40bb-9bfa-ca8e1abca3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>c33b4277-eeaf-4bd7-95f5-23d993f77aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'myFile']</value>
      <webElementGuid>af3d5524-45da-4e26-adb7-2b011c667f11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
