<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Oliver  Liam  Chris  Eve - Copy - Copy</name>
   <tag></tag>
   <elementGuidId>137f6acd-2a5d-439c-ba74-eec72dff5139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='agents']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#agents</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a977ba71-1be3-4d92-b30f-a3c56c3450e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agens</value>
      <webElementGuid>d9d940ca-8db9-4d4b-9fd7-29938169421f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agents</value>
      <webElementGuid>c372c3c5-7aa1-4ff0-903b-6767b256d427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Oliver
  Liam
  Chris
  Eve
</value>
      <webElementGuid>e6f717ce-7ed6-492a-a227-c0533cbc8f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agents&quot;)</value>
      <webElementGuid>590cdfbd-1828-47d3-a9f4-0068943651f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='agents']</value>
      <webElementGuid>8586ea49-0f7e-44eb-89d4-0e14af374959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose an agent:'])[1]/following::select[1]</value>
      <webElementGuid>6a17b615-6874-44a3-b00f-535baf49b08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'agents', '&quot;', ')/option[1]')])[1]/preceding::select[1]</value>
      <webElementGuid>218f5e78-da45-4000-a828-1c733e493707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>80e1a8b2-7e08-4aae-9f7d-253b7ef950ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'agens' and @id = 'agents' and (text() = '
  Oliver
  Liam
  Chris
  Eve
' or . = '
  Oliver
  Liam
  Chris
  Eve
')]</value>
      <webElementGuid>132dee65-fbb4-497b-9206-ce23597455de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
