<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddCountry</name>
   <tag></tag>
   <elementGuidId>1af921e5-a338-415d-b96b-ca5d4c9e039d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-component-select-country']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>1e70174f-99f7-40e4-a589-5b926a34936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>If you're seeing this message, that means &lt;strong>JavaScript has been disabled on your browser&lt;/strong>, please &lt;strong>enable JS&lt;/strong> to make this app work.Retirement planningHow much do I need to save ?I would like to retire inCountry​and would like to save in Currency​Currency.I amAge​years old and would like to retire when I amAge​My monthly income is select ​and I spend  select ​every month.So far I have saved select ​and will save select ​monthly for my retirement.When I retire I would like my lifestyle to beLifestyle​Assumed valuesInflation   %Growth Rate %Assumed values are based on the retirement country selected but you can  input your own values if requiredStart Risk Questionnaireid(&quot;menu-country&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root MenuItemWrapper-sc-nayo7o-0 ezNomD MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-focusVisible Mui-focusVisible&quot;]CountryArgentinaAustraliaAzerbaijanBahrainBrazilCanadaChileChinaColombiaCosta RicaCroatiaCzech RepublicDenmarkEgyptEuro areaGuatemalaHondurasHong KongHungaryIndiaIndonesiaIsraelJapanJordanKuwaitLebanonMalaysiaMexicoMoldovaNew ZealandNicaraguaNorwayOmanPakistanPeruPhilippinesPolandQatarRomaniaRussiaSaudi ArabiaSingaporeSouth AfricaSouth KoreaSri LankaSwedenSwitzerlandTaiwanThailandTurkeyUkraineUnited Arab EmiratesUnited KingdomUnited StatesUruguayVietnam</value>
      <webElementGuid>8b9c45cc-99fe-48f3-a240-277a57c20376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>a4805864-9306-420b-bb90-ea53c8cddbaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>965dd765-9b3d-4087-9c57-d40dfc29cf82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = concat(&quot;If you&quot; , &quot;'&quot; , &quot;re seeing this message, that means &lt;strong>JavaScript has been disabled on your browser&lt;/strong>, please &lt;strong>enable JS&lt;/strong> to make this app work.Retirement planningHow much do I need to save ?I would like to retire inCountry​and would like to save in Currency​Currency.I amAge​years old and would like to retire when I amAge​My monthly income is select ​and I spend  select ​every month.So far I have saved select ​and will save select ​monthly for my retirement.When I retire I would like my lifestyle to beLifestyle​Assumed valuesInflation   %Growth Rate %Assumed values are based on the retirement country selected but you can  input your own values if requiredStart Risk Questionnaireid(&quot;menu-country&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root MenuItemWrapper-sc-nayo7o-0 ezNomD MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-focusVisible Mui-focusVisible&quot;]CountryArgentinaAustraliaAzerbaijanBahrainBrazilCanadaChileChinaColombiaCosta RicaCroatiaCzech RepublicDenmarkEgyptEuro areaGuatemalaHondurasHong KongHungaryIndiaIndonesiaIsraelJapanJordanKuwaitLebanonMalaysiaMexicoMoldovaNew ZealandNicaraguaNorwayOmanPakistanPeruPhilippinesPolandQatarRomaniaRussiaSaudi ArabiaSingaporeSouth AfricaSouth KoreaSri LankaSwedenSwitzerlandTaiwanThailandTurkeyUkraineUnited Arab EmiratesUnited KingdomUnited StatesUruguayVietnam&quot;) or . = concat(&quot;If you&quot; , &quot;'&quot; , &quot;re seeing this message, that means &lt;strong>JavaScript has been disabled on your browser&lt;/strong>, please &lt;strong>enable JS&lt;/strong> to make this app work.Retirement planningHow much do I need to save ?I would like to retire inCountry​and would like to save in Currency​Currency.I amAge​years old and would like to retire when I amAge​My monthly income is select ​and I spend  select ​every month.So far I have saved select ​and will save select ​monthly for my retirement.When I retire I would like my lifestyle to beLifestyle​Assumed valuesInflation   %Growth Rate %Assumed values are based on the retirement country selected but you can  input your own values if requiredStart Risk Questionnaireid(&quot;menu-country&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root MenuItemWrapper-sc-nayo7o-0 ezNomD MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-focusVisible Mui-focusVisible&quot;]CountryArgentinaAustraliaAzerbaijanBahrainBrazilCanadaChileChinaColombiaCosta RicaCroatiaCzech RepublicDenmarkEgyptEuro areaGuatemalaHondurasHong KongHungaryIndiaIndonesiaIsraelJapanJordanKuwaitLebanonMalaysiaMexicoMoldovaNew ZealandNicaraguaNorwayOmanPakistanPeruPhilippinesPolandQatarRomaniaRussiaSaudi ArabiaSingaporeSouth AfricaSouth KoreaSri LankaSwedenSwitzerlandTaiwanThailandTurkeyUkraineUnited Arab EmiratesUnited KingdomUnited StatesUruguayVietnam&quot;))]</value>
      <webElementGuid>4ab4b3dd-88b6-4453-ad22-539650f84f36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
